# Generated by Django 5.2 on 2025-04-23 04:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('issuing_organization', models.CharField(default='Your Organization Name', max_length=200)),
                ('template_image', models.ImageField(blank=True, null=True, upload_to='certificate_templates/')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.CharField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_method', models.CharField(blank=True, choices=[('ONLINE_EXAM', 'Online Exam'), ('PROCTORED_EXAM', 'Proctored Exam'), ('IN_PERSON', 'In-Person Training/Exam'), ('BADGE_ONLY', 'Digital Badge Only'), ('ONLINE_COURSE', 'Online Course (Self-paced)'), ('VILT', 'Virtual Instructor-Led Training')], max_length=50, null=True)),
                ('certification_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.certificationtype')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('qr_code_data', models.URLField(blank=True, max_length=500)),
                ('client', models.ForeignKey(limit_choices_to={'is_employee': False}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.certificationtype')),
            ],
            options={
                'ordering': ['-issue_date'],
                'unique_together': {('client', 'certification_type')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled/Confirmed'), ('ATTENDED', 'Attended'), ('CANCELLED_BY_USER', 'Cancelled by User'), ('CANCELLED_BY_ADMIN', 'Cancelled by Admin'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(limit_choices_to={'is_employee': False}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.trainingcourse')),
            ],
            options={
                'ordering': ['-event_datetime', '-created_at'],
                'unique_together': {('client', 'course', 'event_datetime')},
            },
        ),
    ]
