# Generated by Django 5.2 on 2025-04-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_trainingcourse_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='generated_certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='generated_certificates/'),
        ),
    ]
