# Generated by Django 5.2 on 2025-04-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificate_generated_certificate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationtype',
            name='price',
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='cert_id_color',
            field=models.CharField(default='#555555', help_text='Hex color code for ID', max_length=7),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='cert_id_font_size',
            field=models.PositiveIntegerField(default=10, help_text='Font size for certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='cert_id_x',
            field=models.PositiveIntegerField(default=50, help_text='X coordinate for certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='cert_id_y',
            field=models.PositiveIntegerField(default=350, help_text='Y coordinate for certificate ID'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='date_color',
            field=models.CharField(default='#333333', help_text='Hex color code for date', max_length=7),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='date_font_size',
            field=models.PositiveIntegerField(default=14, help_text='Font size for issue date'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='date_x',
            field=models.PositiveIntegerField(default=50, help_text='X coordinate for issue date'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='date_y',
            field=models.PositiveIntegerField(default=300, help_text='Y coordinate for issue date'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='name_color',
            field=models.CharField(default='#000000', help_text='Hex color code for name (e.g., #000000)', max_length=7),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='name_font_size',
            field=models.PositiveIntegerField(default=30, help_text='Font size for recipient name'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='name_x',
            field=models.PositiveIntegerField(default=50, help_text='X coordinate for recipient name'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='name_y',
            field=models.PositiveIntegerField(default=200, help_text='Y coordinate for recipient name'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='qr_code_size',
            field=models.PositiveIntegerField(default=100, help_text='Size (width & height) of QR Code in pixels'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='qr_code_x',
            field=models.PositiveIntegerField(default=600, help_text='X coordinate for QR Code (top-left)'),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='qr_code_y',
            field=models.PositiveIntegerField(default=300, help_text='Y coordinate for QR Code (top-left)'),
        ),
        migrations.AlterField(
            model_name='certificationtype',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Optional: Validity duration in days from issue date.', null=True),
        ),
        migrations.AlterField(
            model_name='certificationtype',
            name='template_image',
            field=models.ImageField(blank=True, help_text='Background image/design for the certificate.', null=True, upload_to='certificate_templates/'),
        ),
    ]
