# Generated by Django 5.2 on 2025-04-30 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_certificationtype_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='earning_criteria',
            field=models.TextField(blank=True, help_text='Describe how this certificate is earned (e.g., exam details, course completion).', null=True),
        ),
        migrations.AddField(
            model_name='certificationtype',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='certification_types', to='core.skill'),
        ),
    ]
